export {
  sailpointFetch,
  sailpointCount,
  tenantBaseUrl,
  type SailpointClientOptions,
  type SailpointFetchError,
  type SailpointFetchResult,
} from "./client";

export {
  getTransform,
  listTransforms,
  createTransform,
  updateTransform,
  deleteTransform,
  type TransformPayload,
  type TransformRecord,
  type CreateOrUpdateResult,
  type DeleteResult,
  type FetchResult,
} from "./transforms-api";

export {
  listIdentities,
  getIdentity,
  getIdentityAccounts,
  getIdentityAccess,
  processIdentity,
  processIdentities,
  listIdentityProfiles,
  searchIdentities,
  countIdentities,
  buildIdentitySearchQuery,
  type IdentitySummary,
  type IdentityDetail,
  type IdentityProfileRef,
  type IdentityManagerRef,
  type IdentityLifecycleState,
  type IdentityProfileSummary,
  type IdentityAccount,
  type IdentityAccessItem,
  type IdentityAccessItemType,
  type IdentitySearchHit,
  type ListIdentitiesParams,
  type SearchIdentitiesParams,
  type ListResult,
  type ProcessIdentityResult,
} from "./identities-api";
