export {
  sailpointFetch,
  sailpointCount,
  tenantBaseUrl,
  type SailpointClientOptions,
  type SailpointFetchError,
  type SailpointFetchResult,
} from "./client";

export {
  getTransform,
  listTransforms,
  createTransform,
  updateTransform,
  deleteTransform,
  type TransformPayload,
  type TransformRecord,
  type CreateOrUpdateResult,
  type DeleteResult,
  type FetchResult,
} from "./transforms-api";

export {
  listIdentities,
  getIdentity,
  getIdentityAccounts,
  getIdentityAccess,
  processIdentity,
  processIdentities,
  listIdentityProfiles,
  getIdentityProfileLifecycleStates,
  searchIdentities,
  countIdentities,
  buildIdentitySearchQuery,
  type IdentitySummary,
  type IdentityDetail,
  type IdentityProfileRef,
  type IdentityManagerRef,
  type IdentityLifecycleState,
  type IdentityProfileSummary,
  type IdentityProfileLifecycleState,
  type IdentityAccount,
  type IdentityAccessItem,
  type IdentityAccessItemType,
  type IdentitySearchHit,
  type ListIdentitiesParams,
  type SearchIdentitiesParams,
  type ListResult,
  type ProcessIdentityResult,
} from "./identities-api";

export {
  listSources,
  getSource,
  getSourceSchemas,
  getSourceAccounts,
  getSourceAggregationStatus,
  triggerAggregation,
  countAccounts,
  countEntitlements,
  recorrelateAccounts,
  disableAccounts,
  refreshAccountsFromSource,
  getSchemaMappings,
  getCorrelationConfig,
  type SourceRef,
  type SourceSummary,
  type SourceDetail,
  type SourceSchema,
  type SourceSchemaAttribute,
  type SourceAccount,
  type SourceAggregationStatus,
  type ListSourcesParams,
  type GetSourceAccountsParams,
  type AggregationType,
  type TriggerAggregationParams,
  type TriggerAggregationResult,
  type AccountActionItemResult,
  type BulkAccountActionResult,
  type SchemaMappings,
  type SchemaMappingEntry,
  type CorrelationConfig,
  type CorrelationAttributeAssignment,
} from "./sources-api";

export {
  listIdentityAttributes,
  getIdentityAttribute,
  getAttributeUsageInTransforms,
  getAttributeUsageInIdentityProfiles,
  getIdentityAttributesUsageSnapshot,
  type IdentityAttributeSummary,
  type IdentityAttributeDetail,
  type IdentityAttributeSource,
  type AttributeUsageInTransform,
  type AttributeUsageInIdentityProfile,
  type IdentityAttributeUsageSnapshot,
  type ListIdentityAttributesParams,
} from "./identity-attributes-api";

export {
  getIdentityAttributesReferencingTransform,
  getIdentityAttributeValueDistribution,
  type IdentityAttributeReferencingTransform,
  type IdentityAttributeValueBucket,
  type GetIdentityAttributeValueDistributionParams,
} from "./identity-attributes-api";

export {
  computeAttributeDrift,
  deriveDriftTier,
  getAttributeProfileMapping,
  type AttributeDriftInput,
  type AttributeDriftResult,
  type DriftTier,
} from "./identity-attributes-api";
